name: Iris sync
on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  coverage:
    name: "Coverage report generation"
    runs-on: github-ubuntu-latest-s
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      - name: Configure poetry
        uses: ./.github/actions/config-poetry
      - run: |
          poetry run pytest --cov-report=xml:coverage.xml --cov-config=pyproject.toml --cov=src --cov-branch tests
          poetry run mypy src/ > mypy-report.txt || true
      - name: Upload coverage artifacts
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: coverage-reports
          path: |
            coverage.xml
            mypy-report.txt

  shadow-scans:
    name: Shadow Scans
    needs: coverage
    runs-on: github-ubuntu-latest-s
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

      - name: Download coverage artifacts
        uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
        with:
          name: coverage-reports

      - name: Build and run shadow scan
        uses: SonarSource/ci-github-actions/build-poetry@v1
        with:
          sonar-platform: next
          run-shadow-scans: true
          artifactory-reader-role: private-reader
          artifactory-deployer-role: qa-deployer

  iris:
    name: IRIS Sync
    needs: shadow-scans
    runs-on: github-ubuntu-latest-s
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Run IRIS Analysis
        uses: SonarSource/unified-dogfooding-actions/run-iris@v1
        with:
          primary_project_key: "SonarSource_sonar-scanner-python"
          primary_platform: "Next"
          shadow1_project_key: "SonarSource_sonar-scanner-python"
          shadow1_platform: "SQC-EU"
          shadow2_project_key: "SonarSource_sonar-scanner-python"
          shadow2_platform: "SQC-US"
